# Generated by Django 4.2.1 on 2023-05-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmy_app", "0002_remove_myuser_contact_no_myuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_ceo",
            field=models.BooleanField(default=False),
        ),
    ]
