# Generated by Django 4.2.1 on 2023-05-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmy_app", "0004_myuser_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
