# Generated by Django 4.2.1 on 2023-05-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cmy_app", "0005_alter_myuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="username",
        ),
    ]
